---
version: "3.8"
name:    "csv_mapper"
services:
  django:
    container_name: "django"
    build:
      context: "./docker/django"
      dockerfile: "dockerfile"
    restart: "unless-stopped"
    privileged: false
    user: "1000:1000"
    read_only: true
    depends_on:
      mysql:
        condition: "service_healthy"
    secrets:
      - "mysql_django_password"
    environment:
      - "MYSQL_HOST=10.100.0.20"
      - "MYSQL_PORT=3306"
      - "MYSQL_DATABASE=csv_mapper"
      - "MYSQL_USER=django"
      - "MYSQL_PASSWORD_FILE=/run/secrets/mysql_django_password"
    networks:
      main:
        ipv4_address: "10.100.0.10"
    ports:
      - "8000:8000"
    volumes:
      - "django_src:/code"
  mysql:
    container_name: "mysql"
    image: "mysql:latest"
    restart: "unless-stopped"
    privileged: false
    user: "1000:1000"
    secrets:
      - "mysql_root_password"
      - "mysql_django_password"
    environment:
      - "MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password"
      - "MYSQL_DATABASE=csv_mapper"
      - "MYSQL_USER=django"
      - "MYSQL_PASSWORD_FILE=/run/secrets/mysql_django_password"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=no"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      retries: 5
      interval: "5s"
      start_period: "5s"
      timeout: "10s"
    networks:
      main:
        ipv4_address: "10.100.0.20"
    volumes:
      - "mysql_data:/var/lib/mysql"
  phpmyadmin:
    container_name: "phpmyadmin"
    image:          "phpmyadmin/phpmyadmin:latest"
    restart:        "unless-stopped"
    privileged:     false
    depends_on:
      - "mysql"
    environment:
      - "PMA_HOST=10.100.0.20"
      - "PMA_PORT=3306"
      - "PMA_ARBITRARY=0"
    networks:
      main:
        ipv4_address: "10.100.0.30"
    ports:
      - "18080:80"
secrets:
  mysql_root_password:
    file: "./.secrets/mysql_root_password"
  mysql_django_password:
    file: "./.secrets/mysql_django_password"
volumes:
  django_src:
    driver: "local"
    driver_opts:
      type: "none"
      o: "bind"
      device: "./src"
  mysql_data:
    driver: "local"
    driver_opts:
      type: "none"
      o: "bind"
      device: "./data/mysql"
networks:
  main:
    driver: "bridge"
    ipam:
      config:
        - subnet: "10.100.0.0/24"
          gateway: "10.100.0.1"
