# Generated by Django 5.0 on 2023-12-08 14:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=256)),
                ('has_header', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'source',
                'db_table_comment': 'Describes the location of CSV data.',
            },
        ),
        migrations.CreateModel(
            name='SourceColumnConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_id', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('column_name', models.CharField(max_length=128)),
                ('transform_name', models.CharField(choices=[('none', '')], default='none', max_length=128)),
                ('unit', models.CharField(max_length=32)),
                ('source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sourcemodel')),
            ],
            options={
                'db_table': 'source_column_config',
                'db_table_comment': 'Contains configuration for individual columns of data-sources.',
            },
        ),
        migrations.CreateModel(
            name='GraphModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sourcemodel')),
            ],
            options={
                'db_table': 'graph',
                'db_table_comment': 'Contains graphs',
            },
        ),
    ]
