# Generated by Django 5.0 on 2023-12-09 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='name',
            field=models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='graphdataset',
            name='label',
            field=models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
