# Generated by Django 5.0 on 2023-12-07 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='datacolumnconfigmodel',
            table_comment='Contains configuration for individual columns of data-sources.',
        ),
        migrations.AlterModelTableComment(
            name='datasourcemodel',
            table_comment='Describes the location of CSV data.',
        ),
        migrations.AlterModelTableComment(
            name='graphmodel',
            table_comment='Contains graphs',
        ),
    ]
