# Generated by Django 5.0 on 2023-12-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphdataset',
            name='plot_type',
            field=models.CharField(choices=[('none', 'none'), ('line', 'line'), ('bar', 'bar'), ('pie', 'pie'), ('doughnut', 'doughnut'), ('polar_area', 'polarArea'), ('radar', 'radar'), ('scatter', 'scatter')], max_length=16),
        ),
    ]
