# Generated by Django 5.0 on 2023-12-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_datacolumnconfigmodel_table_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourcemodel',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='graphmodel',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
