# Generated by Django 5.0 on 2023-12-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_graphdataset_plot_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphdataset',
            name='plot_type',
            field=models.CharField(choices=[('none', 'none'), ('line', 'line'), ('bar', 'bar'), ('bubble', 'bubble'), ('pie', 'pie'), ('doughnut', 'doughnut'), ('polar_area', 'polarArea'), ('radar', 'radar'), ('scatter', 'scatter')], max_length=16),
        ),
    ]
