name: Django Tests
on:
  push:
    branches:
      - master
      - stable
jobs:
  django_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create mock filesystem
        run: |
          mkdir -p ./src/logs
          touch ./src/django_secret_key
          openssl rand -hex 64 > ./src/django_secret_key
      - name: Run tests
        working-directory: ./src
        env:
          DJANGO_SECRET_KEY_FILE: ./django_secret_key
          DJANGO_LOG_DIRECTORY: ./logs
          DJANGO_LOG_LEVEL: WARNING
          DJANGO_ENVIRONMENT: DEVELOPMENT
          MYSQL_MAIN_DATABASE: main
          MYSQL_GRAPH_DATABASE: graph
        run: python manage.py test