name: Build and Publish Docker Image
on:
  push:
    branches:
      - stable
jobs:
  build-and-publish:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository:
    - name: Checkout Code
      uses: actions/checkout@v3
    # Set up Docker:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    # Log in to GitHub Docker Registry:
    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    # Get the current date and commit SHA:
    - name: Generate Image Tag
      id: vars
      run: |
        echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
        echo "sha=${{ github.sha::0:7 }}" >> $GITHUB_ENV
        echo "image_tag=${{ env.date }}-${{ env.sha }}" >> $GITHUB_ENV
    # Build the Docker image
    - name: Build Docker Image
      run: |
        docker build \
          --file ./docker/django/dockerfile \
          --tag ghcr.io/${{ github.repository }}/csv:${{ env.image_tag }} \
          ./docker/django
    # Push the Docker image to GitHub Packages
    - name: Push Docker Image
      run: |
        docker push ghcr.io/${{ github.repository }}/csv:${{ env.image_tag }}