name: Security Scan
on:
  push:
    branches:
      - master
      - stable
jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docker/django/requirements.txt
      - name: Create mock filesystem
        run: |
          mkdir -p ./src/logs
      - name: Remove test directories
        run: |
          find ./src -type d -name "tests" -exec rm -rf {} +
      - name: Run Bandit (Static Code Analysis)
        run: |
          pip install bandit
          bandit -r ./src
      - name: Run Safety (Dependency Vulnerability Scan)
        run: |
          pip install safety
          safety check -r docker/django/requirements.txt